# Generated by Django 2.0 on 2017-12-05 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notacertablog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='check_empresa',
            field=models.CharField(choices=[('s', 'Sim'), ('n', 'Não')], default='s', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='check_ramo',
            field=models.CharField(choices=[('s', 'Sim'), ('n', 'Não')], default='s', max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='empresa',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='ramo',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
