# Generated by Django 2.0 on 2017-12-05 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notacertablog', '0002_auto_20171205_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='check_empresa',
            field=models.CharField(blank=True, choices=[('s', 'Sim'), ('n', 'Não')], default='s', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='check_ramo',
            field=models.CharField(blank=True, choices=[('s', 'Sim'), ('n', 'Não')], default='s', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='cidade',
            field=models.CharField(default='Salvador', max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='empresa',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='ramo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
